### PR TITLE
issue #64: A comprehensive guide to deployment of the OBA docker Imag…

### PR DESCRIPTION
**Pull request by AlexNduta**
…e to Azure

Issue #64 My assumption is that the IaC  artifact will be provided separately. The file is still open for amendments to be inline with  the choice of tools used in issue #62 and #63

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
we're not ready to document the azure deployment strategy. the work in #62 and #63 needs to be done first.

**Comment by AlexNduta** [comment]
Is there anyone working on #62 ? 

> we're not ready to document the azure deployment strategy. the work in #62 and #63 needs to be done first.

**Comment by aaronbrethorst** [comment]
@AlexNduta I'm holding onto #62 for the moment, but thank you for checking in.

**Comment by AlexNduta** [comment]
Ok @aaronbrethorst , thanks for the feedback. I really appreciate.

**Pull request closed without merging**
